alias adb=$HOME/android-sdk-linux/platform-tools/adb
function adbsudo {
sudo $HOME/android-sdk-linux/platform-tools/adb "$@"
}
alias android=$HOME/android-sdk-linux/tools/android
function adbrun {
sudo $HOME/android-sdk-linux/platform-tools/adb shell am start -n $1/$1.MainActivity
}
function adbimg {
sudo $HOME/android-sdk-linux/platform-tools/adb shell screencap -p /sdcard/$1
sudo $HOME/android-sdk-linux/platform-tools/adb pull /sdcard/$1
sudo $HOME/android-sdk-linux/platform-tools/adb shell rm /sdcard/$1
}
function adbvid {
echo 'Can Add Time limit args: --time-limit seconds'
echo 'Defaults to 3min.'
echo '<Ctrl>  + <C> to exit anytime'
echo 'Requires Android 4.4.x (API 19) or greater.'
sudo $HOME/android-sdk-linux/platform-tools/adb shell screenrecord /sdcard/$1
sudo $HOME/android-sdk-linux/platform-tools/adb pull /sdcard/$1
sudo $HOME/android-sdk-linux/platform-tools/adb shell rm /sdcard/$1
}
function adbinstall {
sudo $HOME/android-sdk-linux/platform-tools/adb install -r %1
}
function adblogcat {
sudo $HOME/android-sdk-linux/platform-tools/adb shell logcat
}
function adbtext {
adbsudo shell input text "$@"
}
function adbkeys {
adbsudo shell input keyevent "$@"
}
function r {
adbkeys 22
}
function l {
adbkeys 21
}
function u {
adbkeys 19
}
function d {
adbkeys 20
}
function e {
adbkeys 23
}
function b {
adbkeys 4
}
