(** This GCode was generated by ReplicatorG 0040 **)
(*  using Skeinforge (50)  *)
(*  for a Single headed The Replicator  *)
(*  on 2016/04/24 12:29:25 (-0400) *)
(**** start.gcode for The Replicator, single head ****)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
M109 S110 T0 (set HBP temperature)
M104 S210 T0 (set extruder temperature) (temp updated by printOMatic)
(**** begin homing ****)
G162 X Y F2500 (home XY axes maximum)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 (move Z to "0")
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
M73 P1 (display progress)
(**** end homing ****)
G1 X-110.5 Y-74 Z150 F3300.0 (move to waiting position)
G130 X20 Y20 Z20 A20 B20 (Lower stepper Vrefs while heating)
M6 T0 (wait for toolhead, and HBP to reach temperature)
G130 X127 Y127 Z40 A127 B127 (Set Stepper motor Vref to defaults)
M108 R3.0 T0
G0 X-110.5 Y-74 (Position Nozzle)
G0 Z0.6      (Position Height)
M108 R5.0    (Set Extruder Speed)
M101         (Start Extruder)
G4 P2000     (Create Anchor)
(**** end of start.gcode ****)
(<format> skeinforge gcode </format>)
(<version> 12.03.14 </version>)
M73 P2 (display progress)
(<created> 16.04.24|12:29 </created>)
(<extruderInitialization>)
(<craftTypeName> extrusion </craftTypeName>)
M105
(<decimalPlacesCarried> 3 </decimalPlacesCarried>)
(<layerThickness> 0.3 </layerThickness>)
(<infillWidth> 0.4 </infillWidth>)
(<volumeFraction> 0.82 </volumeFraction>)
(<infillPerimeterOverlap> 0.3 </infillPerimeterOverlap>)
(<sharpestProduct> 0.866 </sharpestProduct>)
(<layerHeight> 0.3 </layerHeight>)
(<threadSequenceString> loops edge infill </threadSequenceString>)
(<maximumZFeedRatePerSecond> 999.0 </maximumZFeedRatePerSecond>)
(<objectFirstLayerFeedRateInfillMultiplier> 0.9 </objectFirstLayerFeedRateInfillMultiplier>)
M73 P3 (display progress)
(<operatingFeedRatePerSecond> 85.0 </operatingFeedRatePerSecond>)
(<objectFirstLayerFlowRateInfillMultiplier> 0.8 </objectFirstLayerFlowRateInfillMultiplier>)
(<operatingFlowRate> 85.0 </operatingFlowRate>)
(<orbitalFeedRatePerSecond> 0.0 </orbitalFeedRatePerSecond>)
(<travelFeedRatePerSecond> 110.0 </travelFeedRatePerSecond>)
M126
(<edgeWidth> 0.4 </edgeWidth>)
(<perimeterWidth> 0.4 </perimeterWidth>)
(<profileName> ABS </profileName>)
(<settings>)
(<setting> alteration Activate_Alteration True </setting>)
(<setting> alteration Name_of_End_File:  </setting>)
(<setting> alteration Name_of_Start_File:  </setting>)
(<setting> alteration Remove_Redundant_Mcode True </setting>)
M73 P4 (display progress)
(<setting> alteration Replace_Variable_with_Setting True </setting>)
(<setting> comb Activate_Comb True </setting>)
(<setting> comb Running_Jump_Space_(mm): 2.0 </setting>)
(<setting> cool Activate_Cool True </setting>)
(<setting> cool Bridge_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Orbit False </setting>)
(<setting> cool Slow_Down True </setting>)
(<setting> cool Maximum_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Minimum_Layer_Time_(seconds): 5.0 </setting>)
(<setting> cool Minimum_Orbital_Radius_(millimeters): 10.0 </setting>)
(<setting> cool Name_of_Cool_End_File: cool_end.gcode </setting>)
(<setting> cool Name_of_Cool_Start_File: cool_start.gcode </setting>)
(<setting> cool Orbital_Outset_(millimeters): 2.0 </setting>)
(<setting> cool Turn_Fan_On_at_Beginning True </setting>)
M73 P5 (display progress)
(<setting> cool Turn_Fan_Off_at_Ending True </setting>)
(<setting> dimension Activate_Dimension True </setting>)
(<setting> dimension Absolute_Extrusion_Distance True </setting>)
(<setting> dimension Relative_Extrusion_Distance False </setting>)
(<setting> dimension Extruder_Retraction_Speed_(mm/s): 20.0 </setting>)
(<setting> dimension Filament_Diameter_(mm): 1.75 </setting>)
(<setting> dimension Filament_Packing_Density_(ratio): 0.85 </setting>)
(<setting> dimension Maximum_E_Value_before_Reset_(float): 91234.0 </setting>)
(<setting> dimension Minimum_Travel_for_Retraction_(millimeters): 1.0 </setting>)
(<setting> dimension Retract_Within_Island False </setting>)
(<setting> dimension Retraction_Distance_(millimeters): 1.0 </setting>)
(<setting> dimension Restart_Extra_Distance_(millimeters): 0.0 </setting>)
(<setting> export Activate_Export True </setting>)
(<setting> export Add_Descriptive_Extension False </setting>)
M73 P6 (display progress)
(<setting> export Add_Export_Suffix False </setting>)
(<setting> export Add_Profile_Extension False </setting>)
(<setting> export Add_Timestamp_Extension False </setting>)
(<setting> export Also_Send_Output_To:  </setting>)
(<setting> export Analyze_Gcode True </setting>)
(<setting> export Do_Not_Delete_Comments True </setting>)
(<setting> export Delete_Crafting_Comments False </setting>)
(<setting> export Delete_All_Comments False </setting>)
(<setting> export Do_Not_Change_Output True </setting>)
(<setting> export binary_16_byte False </setting>)
(<setting> export gcode_step False </setting>)
(<setting> export gcode_time_segment False </setting>)
(<setting> export gcode_small False </setting>)
(<setting> export File_Extension: gcode </setting>)
M73 P7 (display progress)
(<setting> export Name_of_Replace_File: replace.csv </setting>)
(<setting> export Save_Penultimate_Gcode False </setting>)
(<setting> fill Activate_Fill True </setting>)
(<setting> fill Diaphragm_Period_(layers): 100 </setting>)
(<setting> fill Diaphragm_Thickness_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Alternating_Solid_Layer_(layers): 1 </setting>)
(<setting> fill Extra_Shells_on_Base_(layers): 1 </setting>)
(<setting> fill Extra_Shells_on_Sparse_Layer_(layers): 1 </setting>)
(<setting> fill Grid_Circle_Separation_over_Perimeter_Width_(ratio): 0.2 </setting>)
(<setting> fill Grid_Extra_Overlap_(ratio): 0.1 </setting>)
(<setting> fill Grid_Junction_Separation_Band_Height_(layers): 10 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_End_(ratio): 0.0 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_Middle_(ratio): 0.0 </setting>)
(<setting> fill Infill_Begin_Rotation_(degrees): 90.0 </setting>)
M73 P8 (display progress)
(<setting> fill Infill_Begin_Rotation_Repeat_(layers): 1 </setting>)
(<setting> fill Infill_Odd_Layer_Extra_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Grid_Circular False </setting>)
(<setting> fill Grid_Hexagonal False </setting>)
(<setting> fill Grid_Rectangular True </setting>)
(<setting> fill Line False </setting>)
(<setting> fill Infill_Perimeter_Overlap_(ratio): 0.3 </setting>)
(<setting> fill Infill_Solidity_(ratio): 0.08 </setting>)
(<setting> fill Sharpest_Angle_(degrees): 60.0 </setting>)
(<setting> fill Solid_Surface_Thickness_(layers): 3 </setting>)
(<setting> fill Lower_Left True </setting>)
(<setting> fill Nearest False </setting>)
(<setting> fill Surrounding_Angle_(degrees): 60.0 </setting>)
(<setting> fill Infill_>_Loops_>_Perimeter False </setting>)
M73 P9 (display progress)
(<setting> fill Infill_>_Perimeter_>_Loops False </setting>)
(<setting> fill Loops_>_Infill_>_Perimeter False </setting>)
(<setting> fill Loops_>_Perimeter_>_Infill True </setting>)
(<setting> fill Perimeter_>_Infill_>_Loops False </setting>)
(<setting> fill Perimeter_>_Loops_>_Infill False </setting>)
(<setting> home Activate_Home True </setting>)
(<setting> home Name_of_Home_File: home.gcode </setting>)
(<setting> jitter Activate_Jitter True </setting>)
(<setting> jitter Jitter_Over_Perimeter_Width_(ratio): 2.0 </setting>)
(<setting> raft Activate_Raft True </setting>)
(<setting> raft Add_Raft,_Elevate_Nozzle,_Orbit: True </setting>)
(<setting> raft Base_Feed_Rate_Multiplier_(ratio): 0.75 </setting>)
(<setting> raft Base_Flow_Rate_Multiplier_(ratio): 0.6 </setting>)
(<setting> raft Base_Infill_Density_(ratio): 0.3 </setting>)
M73 P10 (display progress)
(<setting> raft Base_Layer_Thickness_over_Layer_Thickness: 2.2 </setting>)
(<setting> raft Base_Layers_(integer): 1 </setting>)
(<setting> raft Base_Nozzle_Lift_over_Base_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Initial_Circling: False </setting>)
(<setting> raft Infill_Overhang_over_Extrusion_Width_(ratio): 0.1 </setting>)
(<setting> raft Interface_Feed_Rate_Multiplier_(ratio): 1.5 </setting>)
(<setting> raft Interface_Flow_Rate_Multiplier_(ratio): 0.7 </setting>)
(<setting> raft Interface_Infill_Density_(ratio): 0.4 </setting>)
(<setting> raft Interface_Layer_Thickness_over_Layer_Thickness: 1.8 </setting>)
(<setting> raft Interface_Layers_(integer): 2 </setting>)
(<setting> raft Interface_Nozzle_Lift_over_Interface_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Name_of_Support_End_File: support_end.gcode </setting>)
(<setting> raft Name_of_Support_Start_File: support_start.gcode </setting>)
(<setting> raft Operating_Nozzle_Lift_over_Layer_Thickness_(ratio): 0.0 </setting>)
M73 P11 (display progress)
(<setting> raft Raft_Additional_Margin_over_Length_(%): 2.5 </setting>)
(<setting> raft Raft_Margin_(mm): 2.5 </setting>)
(<setting> raft Support_Cross_Hatch False </setting>)
(<setting> raft Support_Flow_Rate_over_Operating_Flow_Rate_(ratio): 0.7 </setting>)
(<setting> raft Support_Gap_over_Perimeter_Extrusion_Width_(ratio): 0.005 </setting>)
(<setting> raft None True </setting>)
(<setting> raft Empty_Layers_Only False </setting>)
(<setting> raft Everywhere False </setting>)
(<setting> raft Exterior_Only False </setting>)
(<setting> raft Support_Minimum_Angle_(degrees): 45.0 </setting>)
(<setting> speed Activate_Speed True </setting>)
(<setting> speed Add_Flow_Rate: True </setting>)
(<setting> speed Bridge_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Bridge_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
M73 P12 (display progress)
(<setting> speed Duty_Cyle_at_Beginning_(portion): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Ending_(portion): 0.0 </setting>)
(<setting> speed Feed_Rate_(mm/s): 85.0 </setting>)
(<setting> speed Flow_Rate_Setting_(float): 85.0 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Infill_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Infill_Multiplier_(ratio): 0.8 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Orbital_Feed_Rate_over_Operating_Feed_Rate_(ratio): 0.0 </setting>)
(<setting> speed Maximum_Z_Feed_Rate_(mm/s): 999.0 </setting>)
(<setting> speed Perimeter_Feed_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Perimeter_Flow_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Travel_Feed_Rate_(mm/s): 110.0 </setting>)
(</settings>)
M73 P13 (display progress)
(<timeStampPreface> 20160424_122922 </timeStampPreface>)
(<procedureName> carve </procedureName>)
(<procedureName> preface </procedureName>)
(<procedureName> inset </procedureName>)
(<procedureName> fill </procedureName>)
(<procedureName> speed </procedureName>)
(<procedureName> raft </procedureName>)
(<procedureName> jitter </procedureName>)
(<procedureName> comb </procedureName>)
(<procedureName> cool </procedureName>)
(<procedureName> dimension </procedureName>)
(<procedureName> alteration </procedureName>)
(<procedureName> export </procedureName>)
(</extruderInitialization>)
M73 P14 (display progress)
(<crafting>)
;M113 S1.0
;M108 R51.0
(<raftPerimeter>)
(<raftPoint> X12.333 Y-1.698 </raftPoint>)
(<raftPoint> X12.333 Y1.698 </raftPoint>)
(<raftPoint> X13.213 Y4.194 </raftPoint>)
(<raftPoint> X-13.213 Y4.194 </raftPoint>)
(<raftPoint> X-12.333 Y1.698 </raftPoint>)
(<raftPoint> X-12.333 Y-1.698 </raftPoint>)
(<raftPoint> X-13.213 Y-4.194 </raftPoint>)
(<raftPoint> X13.213 Y-4.194 </raftPoint>)
(</raftPerimeter>)
(<layer> 0.528 )
M73 P15 (display progress)
G1 X-11.73 Y-3.69 Z0.53 F6600.0
G1 F1200.0
G1 E1.0
G1 F6600.0
M101
G1 X-11.73 Y3.69 Z0.53 F790.289 E2.676
G1 X-8.8 Y3.69 Z0.53 F790.289 E3.343
G1 X-8.8 Y-3.69 Z0.53 F790.289 E5.019
G1 X-5.87 Y-3.69 Z0.53 F790.289 E5.686
G1 X-5.87 Y3.69 Z0.53 F790.289 E7.362
G1 X-2.93 Y3.69 Z0.53 F790.289 E8.029
G1 X-2.93 Y-3.69 Z0.53 F790.289 E9.705
G1 X0.0 Y-3.69 Z0.53 F790.289 E10.372
G1 X0.0 Y3.69 Z0.53 F790.289 E12.048
M73 P16 (display progress)
G1 X2.93 Y3.69 Z0.53 F790.289 E12.715
G1 X2.93 Y-3.69 Z0.53 F790.289 E14.391
G1 X5.87 Y-3.69 Z0.53 F790.289 E15.058
G1 X5.87 Y3.69 Z0.53 F790.289 E16.734
G1 X8.8 Y3.69 Z0.53 F790.289 E17.401
G1 X8.8 Y-3.69 Z0.53 F790.289 E19.077
G1 X11.73 Y-3.69 Z0.53 F790.289 E19.743
G1 X11.73 Y3.69 Z0.53 F790.289 E21.42
G1 F1200.0
G1 E20.42
G1 F790.289
M103
;M108 R39.43
(</layer>)
M73 P17 (display progress)
(<layer> 1.092 )
G1 X-11.8 Y0.0 Z1.09 F6600.0
G1 F1200.0
G1 E21.42
G1 F6600.0
M101
G1 X11.8 Y0.0 Z1.09 F1564.554 E23.515
G1 X11.8 Y-1.8 Z1.09 F1564.554 E23.675
G1 X-11.8 Y-1.8 Z1.09 F1564.554 E25.77
G1 X-11.8 Y-3.6 Z1.09 F1564.554 E25.93
G1 X11.8 Y-3.6 Z1.09 F1564.554 E28.026
G1 F1200.0
G1 E27.026
G1 F1564.554
M73 P18 (display progress)
M103
G1 X11.8 Y1.8 Z1.09 F6600.0
G1 F1200.0
G1 E28.026
G1 F6600.0
M101
G1 X-11.8 Y1.8 Z1.09 F1564.554 E30.121
G1 X-11.8 Y3.6 Z1.09 F1564.554 E30.281
G1 X11.8 Y3.6 Z1.09 F1564.554 E32.376
G1 F1200.0
G1 E31.376
G1 F1564.554
M103
;M108 R39.43
M73 P19 (display progress)
(</layer>)
(<layer> 1.632 )
G1 X-11.8 Y0.0 Z1.63 F6600.0
G1 F1200.0
G1 E32.376
G1 F6600.0
M101
G1 X11.8 Y0.0 Z1.63 F1564.726 E34.472
G1 X11.8 Y-1.8 Z1.63 F1564.726 E34.631
G1 X-11.8 Y-1.8 Z1.63 F1564.726 E36.727
G1 X-11.8 Y-3.6 Z1.63 F1564.726 E36.886
G1 X11.8 Y-3.6 Z1.63 F1564.726 E38.981
G1 F1200.0
G1 E37.981
M73 P20 (display progress)
G1 F1564.726
M103
G1 X11.8 Y1.8 Z1.63 F6600.0
G1 F1200.0
G1 E38.981
G1 F6600.0
M101
G1 X-11.8 Y1.8 Z1.63 F1564.726 E41.077
G1 X-11.8 Y3.6 Z1.63 F1564.726 E41.236
G1 X11.8 Y3.6 Z1.63 F1564.726 E43.332
G1 F1200.0
G1 E42.332
G1 F1564.726
M103
M73 P21 (display progress)
;M108 R18.23
(</layer>)
(<raftLayerEnd> </raftLayerEnd>)
(<layer> 1.89 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z1.89 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z1.89 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z1.89 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z1.89 </boundaryPoint>)
(<edge> outer )
G1 X-5.9 Y-1.93 Z1.89 F6600.0
G1 F1200.0
M73 P22 (display progress)
G1 E43.332
G1 F6600.0
M101
G1 X-5.9 Y-2.05 Z1.89 F1094.064 E43.339
G1 X5.9 Y-2.05 Z1.89 F1094.064 E44.031
G1 X5.9 Y2.05 Z1.89 F1094.064 E44.272
G1 X-5.9 Y2.05 Z1.89 F1094.064 E44.964
G1 X-5.9 Y-1.93 Z1.89 F1094.064 E45.198
G1 F1200.0
G1 E45.198
G1 F1094.064
M103
(</edge>)
(</boundaryPerimeter>)
M73 P23 (display progress)
(<loop> outer )
;M108 R32.42
G1 X-5.5 Y-1.53 Z1.89 F6600.0
G1 F1200.0
G1 E45.198
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z1.89 F2188.128 E45.204
G1 X5.5 Y-1.65 Z1.89 F2188.128 E45.778
G1 X5.5 Y1.65 Z1.89 F2188.128 E45.95
G1 X-5.5 Y1.65 Z1.89 F2188.128 E46.524
G1 X-5.5 Y-1.53 Z1.89 F2188.128 E46.69
G1 F1200.0
G1 E46.69
M73 P24 (display progress)
G1 F2188.128
M103
(</loop>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z0.15 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z0.15 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z0.15 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z0.15 </infillPoint>)
(</infillBoundary>)
G1 X-5.2 Y-1.16 Z1.89 F6600.0
G1 F1200.0
G1 E46.69
G1 F6600.0
M73 P25 (display progress)
M101
G1 X-5.2 Y1.16 Z1.89 F2188.128 E46.811
G1 X-4.8 Y1.37 Z1.89 F2188.128 E46.835
G1 X-4.8 Y-1.37 Z1.89 F2188.128 E46.978
G1 X-4.4 Y-1.37 Z1.89 F2188.128 E46.999
G1 X-4.4 Y1.37 Z1.89 F2188.128 E47.142
G1 X-4.0 Y1.37 Z1.89 F2188.128 E47.162
G1 X-4.0 Y-1.37 Z1.89 F2188.128 E47.305
G1 X-3.6 Y-1.37 Z1.89 F2188.128 E47.326
G1 X-3.6 Y1.37 Z1.89 F2188.128 E47.469
G1 X-3.2 Y1.37 Z1.89 F2188.128 E47.49
G1 X-3.2 Y-1.37 Z1.89 F2188.128 E47.633
G1 X-2.8 Y-1.37 Z1.89 F2188.128 E47.654
G1 X-2.8 Y1.37 Z1.89 F2188.128 E47.797
M73 P26 (display progress)
G1 X-2.4 Y1.37 Z1.89 F2188.128 E47.818
G1 X-2.4 Y-1.37 Z1.89 F2188.128 E47.961
G1 X-2.0 Y-1.37 Z1.89 F2188.128 E47.982
G1 X-2.0 Y1.37 Z1.89 F2188.128 E48.125
G1 X-1.6 Y1.37 Z1.89 F2188.128 E48.145
G1 X-1.6 Y-1.37 Z1.89 F2188.128 E48.288
G1 X-1.2 Y-1.37 Z1.89 F2188.128 E48.309
G1 X-1.2 Y1.37 Z1.89 F2188.128 E48.452
G1 X-0.8 Y1.37 Z1.89 F2188.128 E48.473
G1 X-0.8 Y-1.37 Z1.89 F2188.128 E48.616
G1 X-0.4 Y-1.37 Z1.89 F2188.128 E48.637
G1 X-0.4 Y1.37 Z1.89 F2188.128 E48.78
G1 X0.0 Y1.37 Z1.89 F2188.128 E48.801
G1 X-0.0 Y-1.37 Z1.89 F2188.128 E48.944
M73 P27 (display progress)
G1 X0.4 Y-1.37 Z1.89 F2188.128 E48.965
G1 X0.4 Y1.37 Z1.89 F2188.128 E49.108
G1 X0.8 Y1.37 Z1.89 F2188.128 E49.129
G1 X0.8 Y-1.37 Z1.89 F2188.128 E49.272
G1 X1.2 Y-1.37 Z1.89 F2188.128 E49.292
G1 X1.2 Y1.37 Z1.89 F2188.128 E49.435
G1 X1.6 Y1.37 Z1.89 F2188.128 E49.456
G1 X1.6 Y-1.37 Z1.89 F2188.128 E49.599
G1 X2.0 Y-1.37 Z1.89 F2188.128 E49.62
G1 X2.0 Y1.37 Z1.89 F2188.128 E49.763
G1 X2.4 Y1.37 Z1.89 F2188.128 E49.784
G1 X2.4 Y-1.37 Z1.89 F2188.128 E49.927
G1 X2.8 Y-1.37 Z1.89 F2188.128 E49.948
G1 X2.8 Y1.37 Z1.89 F2188.128 E50.091
M73 P28 (display progress)
G1 X3.2 Y1.37 Z1.89 F2188.128 E50.112
G1 X3.2 Y-1.37 Z1.89 F2188.128 E50.255
G1 X3.6 Y-1.37 Z1.89 F2188.128 E50.275
G1 X3.6 Y1.37 Z1.89 F2188.128 E50.418
G1 X4.0 Y1.37 Z1.89 F2188.128 E50.439
G1 X4.0 Y-1.37 Z1.89 F2188.128 E50.582
G1 X4.4 Y-1.37 Z1.89 F2188.128 E50.603
G1 X4.4 Y1.37 Z1.89 F2188.128 E50.746
G1 X4.8 Y1.37 Z1.89 F2188.128 E50.767
G1 X4.8 Y-1.37 Z1.89 F2188.128 E50.91
G1 X5.2 Y-1.16 Z1.89 F2188.128 E50.933
G1 X5.2 Y1.16 Z1.89 F2188.128 E51.055
G1 F1200.0
G1 E50.055
M73 P29 (display progress)
G1 F2188.128
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R34.95
(</layer>)
(<layer> 2.19 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z2.19 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z2.19 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z2.19 </boundaryPoint>)
M73 P30 (display progress)
(<boundaryPoint> X-6.1 Y2.25 Z2.19 </boundaryPoint>)
(<loop> outer )
G1 X-5.5 Y-1.22 Z2.19 F6600.0
G1 F1200.0
G1 E51.055
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z2.19 F2096.991 E51.08
G1 X5.5 Y-1.65 Z2.19 F2096.991 E51.725
G1 X5.5 Y1.65 Z2.19 F2096.991 E51.919
G1 X-5.5 Y1.65 Z2.19 F2096.991 E52.565
G1 X-5.5 Y-1.22 Z2.19 F2096.991 E52.733
G1 F1200.0
G1 E52.733
M73 P31 (display progress)
G1 F2096.991
M103
(</loop>)
(<edge> outer )
;M108 R17.47
G1 X-5.9 Y-2.02 Z2.19 F6600.0
G1 F1200.0
G1 E52.733
G1 F6600.0
M101
G1 X-5.9 Y-2.05 Z2.19 F1048.496 E52.735
G1 X-5.5 Y-2.05 Z2.19 F1048.496 E52.758
G1 X5.9 Y-2.05 Z2.19 F1048.496 E53.427
G1 X5.9 Y2.05 Z2.19 F1048.496 E53.668
M73 P32 (display progress)
G1 X-5.9 Y2.05 Z2.19 F1048.496 E54.36
G1 X-5.9 Y-2.02 Z2.19 F1048.496 E54.599
G1 F1200.0
G1 E53.599
G1 F1048.496
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z0.45 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z0.45 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z0.45 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z0.45 </infillPoint>)
M73 P33 (display progress)
(</infillBoundary>)
;M108 R34.95
G1 X5.16 Y-1.2 Z2.19 F6600.0
G1 F1200.0
G1 E54.599
G1 F6600.0
M101
G1 X-5.16 Y-1.2 Z2.19 F2096.991 E55.205
G1 X-5.22 Y-0.8 Z2.19 F2096.991 E55.229
G1 X5.22 Y-0.8 Z2.19 F2096.991 E55.842
G1 X5.22 Y-0.4 Z2.19 F2096.991 E55.865
G1 X-5.22 Y-0.4 Z2.19 F2096.991 E56.478
G1 X-5.22 Y0.0 Z2.19 F2096.991 E56.501
G1 X5.22 Y-0.0 Z2.19 F2096.991 E57.114
M73 P34 (display progress)
G1 X5.22 Y0.4 Z2.19 F2096.991 E57.138
G1 X-5.22 Y0.4 Z2.19 F2096.991 E57.751
G1 X-5.22 Y0.8 Z2.19 F2096.991 E57.774
G1 X5.22 Y0.8 Z2.19 F2096.991 E58.387
G1 X5.16 Y1.2 Z2.19 F2096.991 E58.41
G1 X-5.16 Y1.2 Z2.19 F2096.991 E59.016
G1 F1200.0
G1 E58.016
G1 F2096.991
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R35.44
M73 P35 (display progress)
(</layer>)
(<operatingLayerEnd> </operatingLayerEnd>)
(<layer> 2.49 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z2.49 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z2.49 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z2.49 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z2.49 </boundaryPoint>)
(<loop> outer )
G1 X-5.43 Y-1.65 Z2.49 F6600.0
G1 F1200.0
G1 E59.016
M73 P36 (display progress)
G1 F6600.0
M101
G1 X5.5 Y-1.65 Z2.49 F2126.421 E59.658
G1 X5.5 Y1.65 Z2.49 F2126.421 E59.852
G1 X-5.5 Y1.65 Z2.49 F2126.421 E60.497
G1 X-5.5 Y-1.65 Z2.49 F2126.421 E60.691
G1 X-5.43 Y-1.65 Z2.49 F2126.421 E60.695
G1 F1200.0
G1 E60.695
G1 F2126.421
M103
(</loop>)
(<edge> outer )
;M108 R17.72
M73 P37 (display progress)
G1 X-5.43 Y-2.05 Z2.49 F6600.0
G1 F1200.0
G1 E60.695
G1 F6600.0
M101
G1 X5.9 Y-2.05 Z2.49 F1063.211 E61.36
G1 X5.9 Y2.05 Z2.49 F1063.211 E61.601
G1 X-5.9 Y2.05 Z2.49 F1063.211 E62.293
G1 X-5.9 Y-2.05 Z2.49 F1063.211 E62.534
G1 X-5.5 Y-2.05 Z2.49 F1063.211 E62.558
G1 X-5.43 Y-2.05 Z2.49 F1063.211 E62.562
G1 F1200.0
G1 E62.562
G1 F1063.211
M73 P38 (display progress)
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z0.75 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z0.75 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z0.75 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z0.75 </infillPoint>)
(</infillBoundary>)
;M108 R35.44
G1 X-5.2 Y-1.16 Z2.49 F6600.0
G1 F1200.0
G1 E62.562
M73 P39 (display progress)
G1 F6600.0
M101
G1 X-5.2 Y1.16 Z2.49 F2126.421 E62.698
G1 X-4.8 Y1.37 Z2.49 F2126.421 E62.724
G1 X-4.8 Y-1.37 Z2.49 F2126.421 E62.885
G1 X-4.4 Y-1.37 Z2.49 F2126.421 E62.909
G1 X-4.4 Y1.37 Z2.49 F2126.421 E63.07
G1 X-4.0 Y1.37 Z2.49 F2126.421 E63.093
G1 X-4.0 Y-1.37 Z2.49 F2126.421 E63.254
G1 X-3.6 Y-1.37 Z2.49 F2126.421 E63.277
G1 X-3.6 Y1.37 Z2.49 F2126.421 E63.438
G1 X-3.2 Y1.37 Z2.49 F2126.421 E63.462
G1 X-3.2 Y-1.37 Z2.49 F2126.421 E63.622
G1 X-2.8 Y-1.37 Z2.49 F2126.421 E63.646
M73 P40 (display progress)
G1 X-2.8 Y1.37 Z2.49 F2126.421 E63.807
G1 X-2.4 Y1.37 Z2.49 F2126.421 E63.83
G1 X-2.4 Y-1.37 Z2.49 F2126.421 E63.991
G1 X-2.0 Y-1.37 Z2.49 F2126.421 E64.014
G1 X-2.0 Y1.37 Z2.49 F2126.421 E64.175
G1 X-1.6 Y1.37 Z2.49 F2126.421 E64.199
G1 X-1.6 Y-1.37 Z2.49 F2126.421 E64.36
G1 X-1.2 Y-1.37 Z2.49 F2126.421 E64.383
G1 X-1.2 Y1.37 Z2.49 F2126.421 E64.544
G1 X-0.8 Y1.37 Z2.49 F2126.421 E64.567
G1 X-0.8 Y-1.37 Z2.49 F2126.421 E64.728
G1 X-0.4 Y-1.37 Z2.49 F2126.421 E64.752
G1 X-0.4 Y1.37 Z2.49 F2126.421 E64.913
G1 X0.0 Y1.37 Z2.49 F2126.421 E64.936
M73 P41 (display progress)
G1 X-0.0 Y-1.37 Z2.49 F2126.421 E65.097
G1 X0.4 Y-1.37 Z2.49 F2126.421 E65.12
G1 X0.4 Y1.37 Z2.49 F2126.421 E65.281
G1 X0.8 Y1.37 Z2.49 F2126.421 E65.305
G1 X0.8 Y-1.37 Z2.49 F2126.421 E65.465
G1 X1.2 Y-1.37 Z2.49 F2126.421 E65.489
G1 X1.2 Y1.37 Z2.49 F2126.421 E65.65
G1 X1.6 Y1.37 Z2.49 F2126.421 E65.673
G1 X1.6 Y-1.37 Z2.49 F2126.421 E65.834
G1 X2.0 Y-1.37 Z2.49 F2126.421 E65.857
G1 X2.0 Y1.37 Z2.49 F2126.421 E66.018
G1 X2.4 Y1.37 Z2.49 F2126.421 E66.042
G1 X2.4 Y-1.37 Z2.49 F2126.421 E66.203
G1 X2.8 Y-1.37 Z2.49 F2126.421 E66.226
M73 P42 (display progress)
G1 X2.8 Y1.37 Z2.49 F2126.421 E66.387
G1 X3.2 Y1.37 Z2.49 F2126.421 E66.41
G1 X3.2 Y-1.37 Z2.49 F2126.421 E66.571
G1 X3.6 Y-1.37 Z2.49 F2126.421 E66.595
G1 X3.6 Y1.37 Z2.49 F2126.421 E66.755
G1 X4.0 Y1.37 Z2.49 F2126.421 E66.779
G1 X4.0 Y-1.37 Z2.49 F2126.421 E66.94
G1 X4.4 Y-1.37 Z2.49 F2126.421 E66.963
G1 X4.4 Y1.37 Z2.49 F2126.421 E67.124
G1 X4.8 Y1.37 Z2.49 F2126.421 E67.148
G1 X4.8 Y-1.37 Z2.49 F2126.421 E67.308
G1 X5.2 Y-1.16 Z2.49 F2126.421 E67.335
G1 X5.2 Y1.16 Z2.49 F2126.421 E67.471
G1 F1200.0
M73 P43 (display progress)
G1 E66.471
G1 F2126.421
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R27.01
(</layer>)
(<layer> 2.79 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z2.79 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z2.79 </boundaryPoint>)
M73 P44 (display progress)
(<boundaryPoint> X6.1 Y2.25 Z2.79 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z2.79 </boundaryPoint>)
(<loop> outer )
G1 X-5.5 Y-1.41 Z2.79 F6600.0
G1 F1200.0
G1 E67.471
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z2.79 F1620.782 E67.485
G1 X5.5 Y-1.65 Z2.79 F1620.782 E68.131
G1 X5.5 Y1.65 Z2.79 F1620.782 E68.325
G1 X-5.5 Y1.65 Z2.79 F1620.782 E68.97
G1 X-5.5 Y-1.41 Z2.79 F1620.782 E69.15
G1 F1200.0
M73 P45 (display progress)
G1 E69.15
G1 F1620.782
M103
(</loop>)
(<edge> outer )
;M108 R13.51
G1 X-5.74 Y-2.05 Z2.79 F6600.0
G1 F1200.0
G1 E69.15
G1 F6600.0
M101
G1 X-5.5 Y-2.05 Z2.79 F810.391 E69.164
G1 X5.9 Y-2.05 Z2.79 F810.391 E69.833
G1 X5.9 Y2.05 Z2.79 F810.391 E70.074
M73 P46 (display progress)
G1 X-5.9 Y2.05 Z2.79 F810.391 E70.767
G1 X-5.9 Y-2.05 Z2.79 F810.391 E71.007
G1 X-5.74 Y-2.05 Z2.79 F810.391 E71.017
G1 F1200.0
G1 E70.017
G1 F810.391
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z1.05 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z1.05 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z1.05 </infillPoint>)
M73 P47 (display progress)
(<infillPoint> X-5.5 Y1.65 Z1.05 </infillPoint>)
(</infillBoundary>)
;M108 R27.01
G1 X5.22 Y-0.8 Z2.79 F6600.0
G1 F1200.0
G1 E71.017
G1 F6600.0
M101
G1 X5.16 Y-1.2 Z2.79 F1620.782 E71.04
G1 X-5.16 Y-1.2 Z2.79 F1620.782 E71.646
G1 X-5.22 Y-0.8 Z2.79 F1620.782 E71.67
G1 F1200.0
G1 E70.67
G1 F1620.782
M73 P48 (display progress)
M103
G1 X5.22 Y0.4 Z2.79 F6600.0
G1 F1200.0
G1 E71.67
G1 F6600.0
M101
G1 X5.22 Y-0.4 Z2.79 F1620.782 E71.717
G1 X-5.22 Y-0.4 Z2.79 F1620.782 E72.33
G1 X-5.22 Y0.8 Z2.79 F1620.782 E72.4
G1 X-5.16 Y1.2 Z2.79 F1620.782 E72.424
G1 X5.16 Y1.2 Z2.79 F1620.782 E73.03
G1 X5.22 Y0.8 Z2.79 F1620.782 E73.053
G1 F1200.0
G1 E72.053
M73 P49 (display progress)
G1 F1620.782
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R24.86
(</layer>)
(<layer> 3.09 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z3.09 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z3.09 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z3.09 </boundaryPoint>)
M73 P50 (display progress)
(<boundaryPoint> X-6.1 Y2.25 Z3.09 </boundaryPoint>)
(<loop> outer )
G1 X-5.25 Y-1.65 Z3.09 F6600.0
G1 F1200.0
G1 E73.053
G1 F6600.0
M101
G1 X5.5 Y-1.65 Z3.09 F1491.427 E73.684
G1 X5.5 Y1.65 Z3.09 F1491.427 E73.878
G1 X-5.5 Y1.65 Z3.09 F1491.427 E74.524
G1 X-5.5 Y-1.65 Z3.09 F1491.427 E74.717
G1 X-5.25 Y-1.65 Z3.09 F1491.427 E74.732
G1 F1200.0
G1 E74.732
M73 P51 (display progress)
G1 F1491.427
M103
(</loop>)
(<edge> outer )
;M108 R12.43
G1 X-5.25 Y-2.05 Z3.09 F6600.0
G1 F1200.0
G1 E74.732
G1 F6600.0
M101
G1 X5.9 Y-2.05 Z3.09 F745.714 E75.387
G1 X5.9 Y2.05 Z3.09 F745.714 E75.627
G1 X-5.9 Y2.05 Z3.09 F745.714 E76.32
G1 X-5.9 Y-2.05 Z3.09 F745.714 E76.561
M73 P52 (display progress)
G1 X-5.5 Y-2.05 Z3.09 F745.714 E76.584
G1 X-5.25 Y-2.05 Z3.09 F745.714 E76.599
G1 F1200.0
G1 E75.599
G1 F745.714
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z1.35 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z1.35 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z1.35 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z1.35 </infillPoint>)
M73 P53 (display progress)
(</infillBoundary>)
;M108 R24.86
G1 X-0.8 Y-1.37 Z3.09 F6600.0
G1 F1200.0
G1 E76.599
G1 F6600.0
M101
G1 X-4.8 Y-1.37 Z3.09 F1491.427 E76.834
G1 X-5.2 Y-1.16 Z3.09 F1491.427 E76.86
G1 X-5.2 Y1.16 Z3.09 F1491.427 E76.997
G1 X-4.8 Y1.37 Z3.09 F1491.427 E77.023
G1 X-0.8 Y1.37 Z3.09 F1491.427 E77.258
G1 F1200.0
G1 E76.258
M73 P54 (display progress)
G1 F1491.427
M103
G1 X4.8 Y-1.37 Z3.09 F6600.0
G1 F1200.0
G1 E77.258
G1 F6600.0
M101
G1 X-0.4 Y-1.37 Z3.09 F1491.427 E77.563
G1 X-0.4 Y1.37 Z3.09 F1491.427 E77.724
G1 X4.8 Y1.37 Z3.09 F1491.427 E78.029
G1 X5.2 Y1.16 Z3.09 F1491.427 E78.056
G1 X5.2 Y-1.16 Z3.09 F1491.427 E78.192
G1 F1200.0
G1 E77.192
M73 P55 (display progress)
G1 F1491.427
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R26.98
(</layer>)
(<layer> 3.39 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z3.39 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z3.39 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z3.39 </boundaryPoint>)
M73 P56 (display progress)
(<boundaryPoint> X-6.1 Y2.25 Z3.39 </boundaryPoint>)
(<loop> outer )
G1 X-5.5 Y-1.6 Z3.39 F6600.0
G1 F1200.0
G1 E78.192
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z3.39 F1618.548 E78.195
G1 X5.5 Y-1.65 Z3.39 F1618.548 E78.841
G1 X5.5 Y1.65 Z3.39 F1618.548 E79.035
G1 X-5.5 Y1.65 Z3.39 F1618.548 E79.68
G1 X-5.5 Y-1.6 Z3.39 F1618.548 E79.871
G1 F1200.0
G1 E79.871
M73 P57 (display progress)
G1 F1618.548
M103
(</loop>)
(<edge> outer )
;M108 R13.49
G1 X-5.55 Y-2.05 Z3.39 F6600.0
G1 F1200.0
G1 E79.871
G1 F6600.0
M101
G1 X-5.5 Y-2.05 Z3.39 F809.274 E79.874
G1 X5.9 Y-2.05 Z3.39 F809.274 E80.543
G1 X5.9 Y2.05 Z3.39 F809.274 E80.784
G1 X-5.9 Y2.05 Z3.39 F809.274 E81.477
M73 P58 (display progress)
G1 X-5.9 Y-2.05 Z3.39 F809.274 E81.717
G1 X-5.55 Y-2.05 Z3.39 F809.274 E81.738
G1 F1200.0
G1 E80.738
G1 F809.274
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z1.65 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z1.65 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z1.65 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z1.65 </infillPoint>)
M73 P59 (display progress)
(</infillBoundary>)
;M108 R26.98
G1 X5.22 Y-0.8 Z3.39 F6600.0
G1 F1200.0
G1 E81.738
G1 F6600.0
M101
G1 X5.16 Y-1.2 Z3.39 F1618.548 E81.762
G1 X-5.16 Y-1.2 Z3.39 F1618.548 E82.368
G1 X-5.22 Y-0.8 Z3.39 F1618.548 E82.391
G1 F1200.0
G1 E81.391
G1 F1618.548
M103
M73 P60 (display progress)
G1 X5.22 Y0.4 Z3.39 F6600.0
G1 F1200.0
G1 E82.391
G1 F6600.0
M101
G1 X5.22 Y-0.4 Z3.39 F1618.548 E82.438
G1 X-5.22 Y-0.4 Z3.39 F1618.548 E83.051
G1 X-5.22 Y0.8 Z3.39 F1618.548 E83.122
G1 X-5.16 Y1.2 Z3.39 F1618.548 E83.145
G1 X5.16 Y1.2 Z3.39 F1618.548 E83.751
G1 X5.22 Y0.8 Z3.39 F1618.548 E83.775
G1 F1200.0
G1 E82.775
G1 F1618.548
M73 P61 (display progress)
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R24.91
(</layer>)
(<layer> 3.69 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z3.69 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z3.69 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z3.69 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z3.69 </boundaryPoint>)
M73 P62 (display progress)
(<loop> outer )
G1 X-5.5 Y-1.29 Z3.69 F6600.0
G1 F1200.0
G1 E83.775
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z3.69 F1494.866 E83.796
G1 X5.5 Y-1.65 Z3.69 F1494.866 E84.442
G1 X5.5 Y1.65 Z3.69 F1494.866 E84.635
G1 X-5.5 Y1.65 Z3.69 F1494.866 E85.281
G1 X-5.5 Y-1.29 Z3.69 F1494.866 E85.454
G1 F1200.0
G1 E85.454
G1 F1494.866
M73 P63 (display progress)
M103
(</loop>)
(<edge> outer )
;M108 R12.46
G1 X-5.86 Y-2.05 Z3.69 F6600.0
G1 F1200.0
G1 E85.454
G1 F6600.0
M101
G1 X-5.5 Y-2.05 Z3.69 F747.433 E85.474
G1 X5.9 Y-2.05 Z3.69 F747.433 E86.144
G1 X5.9 Y2.05 Z3.69 F747.433 E86.384
G1 X-5.9 Y2.05 Z3.69 F747.433 E87.077
G1 X-5.9 Y-2.05 Z3.69 F747.433 E87.318
M73 P64 (display progress)
G1 X-5.86 Y-2.05 Z3.69 F747.433 E87.32
G1 F1200.0
G1 E86.32
G1 F747.433
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z1.95 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z1.95 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z1.95 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z1.95 </infillPoint>)
(</infillBoundary>)
M73 P65 (display progress)
;M108 R24.91
G1 X-0.8 Y-1.37 Z3.69 F6600.0
G1 F1200.0
G1 E87.32
G1 F6600.0
M101
G1 X-4.8 Y-1.37 Z3.69 F1494.866 E87.555
G1 X-5.2 Y-1.16 Z3.69 F1494.866 E87.582
G1 X-5.2 Y1.16 Z3.69 F1494.866 E87.718
G1 X-4.8 Y1.37 Z3.69 F1494.866 E87.744
G1 X-0.8 Y1.37 Z3.69 F1494.866 E87.979
G1 F1200.0
G1 E86.979
G1 F1494.866
M73 P66 (display progress)
M103
G1 X4.8 Y-1.37 Z3.69 F6600.0
G1 F1200.0
G1 E87.979
G1 F6600.0
M101
G1 X-0.4 Y-1.37 Z3.69 F1494.866 E88.284
G1 X-0.4 Y1.37 Z3.69 F1494.866 E88.445
G1 X4.8 Y1.37 Z3.69 F1494.866 E88.75
G1 X5.2 Y1.16 Z3.69 F1494.866 E88.777
G1 X5.2 Y-1.16 Z3.69 F1494.866 E88.913
G1 F1200.0
G1 E87.913
G1 F1494.866
M73 P67 (display progress)
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R26.96
(</layer>)
(<layer> 3.99 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z3.99 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z3.99 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z3.99 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z3.99 </boundaryPoint>)
M73 P68 (display progress)
(<loop> outer )
G1 X-5.36 Y-1.65 Z3.99 F6600.0
G1 F1200.0
G1 E88.913
G1 F6600.0
M101
G1 X5.5 Y-1.65 Z3.99 F1617.37 E89.551
G1 X5.5 Y1.65 Z3.99 F1617.37 E89.744
G1 X-5.5 Y1.65 Z3.99 F1617.37 E90.39
G1 X-5.5 Y-1.65 Z3.99 F1617.37 E90.584
G1 X-5.36 Y-1.65 Z3.99 F1617.37 E90.592
G1 F1200.0
G1 E90.592
G1 F1617.37
M73 P69 (display progress)
M103
(</loop>)
(<edge> outer )
;M108 R13.48
G1 X-5.36 Y-2.05 Z3.99 F6600.0
G1 F1200.0
G1 E90.592
G1 F6600.0
M101
G1 X5.9 Y-2.05 Z3.99 F808.685 E91.253
G1 X5.9 Y2.05 Z3.99 F808.685 E91.494
G1 X-5.9 Y2.05 Z3.99 F808.685 E92.186
G1 X-5.9 Y-2.05 Z3.99 F808.685 E92.427
G1 X-5.5 Y-2.05 Z3.99 F808.685 E92.451
M73 P70 (display progress)
G1 X-5.36 Y-2.05 Z3.99 F808.685 E92.459
G1 F1200.0
G1 E91.459
G1 F808.685
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z2.25 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z2.25 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z2.25 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z2.25 </infillPoint>)
(</infillBoundary>)
M73 P71 (display progress)
;M108 R26.96
G1 X5.22 Y-0.8 Z3.99 F6600.0
G1 F1200.0
G1 E92.459
G1 F6600.0
M101
G1 X5.16 Y-1.2 Z3.99 F1617.37 E92.482
G1 X-5.16 Y-1.2 Z3.99 F1617.37 E93.089
G1 X-5.22 Y-0.8 Z3.99 F1617.37 E93.112
G1 F1200.0
G1 E92.112
G1 F1617.37
M103
G1 X5.22 Y0.4 Z3.99 F6600.0
M73 P72 (display progress)
G1 F1200.0
G1 E93.112
G1 F6600.0
M101
G1 X5.22 Y-0.4 Z3.99 F1617.37 E93.159
G1 X-5.22 Y-0.4 Z3.99 F1617.37 E93.772
G1 X-5.22 Y0.8 Z3.99 F1617.37 E93.843
G1 X-5.16 Y1.2 Z3.99 F1617.37 E93.866
G1 X5.16 Y1.2 Z3.99 F1617.37 E94.472
G1 X5.22 Y0.8 Z3.99 F1617.37 E94.496
G1 F1200.0
G1 E93.496
G1 F1617.37
M103
M73 P73 (display progress)
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R24.9
(</layer>)
(<layer> 4.29 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z4.29 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z4.29 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z4.29 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z4.29 </boundaryPoint>)
(<loop> outer )
M73 P74 (display progress)
G1 X-5.5 Y-1.48 Z4.29 F6600.0
G1 F1200.0
G1 E94.496
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z4.29 F1493.749 E94.506
G1 X5.5 Y-1.65 Z4.29 F1493.749 E95.152
G1 X5.5 Y1.65 Z4.29 F1493.749 E95.345
G1 X-5.5 Y1.65 Z4.29 F1493.749 E95.991
G1 X-5.5 Y-1.48 Z4.29 F1493.749 E96.175
G1 F1200.0
G1 E96.175
G1 F1493.749
M103
M73 P75 (display progress)
(</loop>)
(<edge> outer )
;M108 R12.45
G1 X-5.67 Y-2.05 Z4.29 F6600.0
G1 F1200.0
G1 E96.175
G1 F6600.0
M101
G1 X-5.5 Y-2.05 Z4.29 F746.875 E96.185
G1 X5.9 Y-2.05 Z4.29 F746.875 E96.854
G1 X5.9 Y2.05 Z4.29 F746.875 E97.095
G1 X-5.9 Y2.05 Z4.29 F746.875 E97.787
G1 X-5.9 Y-2.05 Z4.29 F746.875 E98.028
G1 X-5.67 Y-2.05 Z4.29 F746.875 E98.042
M73 P76 (display progress)
G1 F1200.0
G1 E97.042
G1 F746.875
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z2.55 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z2.55 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z2.55 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z2.55 </infillPoint>)
(</infillBoundary>)
;M108 R24.9
M73 P77 (display progress)
G1 X-0.8 Y-1.37 Z4.29 F6600.0
G1 F1200.0
G1 E98.042
G1 F6600.0
M101
G1 X-4.8 Y-1.37 Z4.29 F1493.749 E98.277
G1 X-5.2 Y-1.16 Z4.29 F1493.749 E98.303
G1 X-5.2 Y1.16 Z4.29 F1493.749 E98.439
G1 X-4.8 Y1.37 Z4.29 F1493.749 E98.466
G1 X-0.8 Y1.37 Z4.29 F1493.749 E98.701
G1 F1200.0
G1 E97.701
G1 F1493.749
M103
M73 P78 (display progress)
G1 X4.8 Y-1.37 Z4.29 F6600.0
G1 F1200.0
G1 E98.701
G1 F6600.0
M101
G1 X-0.4 Y-1.37 Z4.29 F1493.749 E99.006
G1 X-0.4 Y1.37 Z4.29 F1493.749 E99.167
G1 X4.8 Y1.37 Z4.29 F1493.749 E99.472
G1 X5.2 Y1.16 Z4.29 F1493.749 E99.499
G1 X5.2 Y-1.16 Z4.29 F1493.749 E99.635
G1 F1200.0
G1 E98.635
G1 F1493.749
M103
M73 P79 (display progress)
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R34.93
(</layer>)
(<layer> 4.59 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z4.59 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z4.59 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z4.59 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z4.59 </boundaryPoint>)
(<loop> outer )
M73 P80 (display progress)
G1 X-5.5 Y-1.18 Z4.59 F6600.0
G1 F1200.0
G1 E99.635
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z4.59 F2095.936 E99.663
G1 X5.5 Y-1.65 Z4.59 F2095.936 E100.308
G1 X5.5 Y1.65 Z4.59 F2095.936 E100.502
G1 X-5.5 Y1.65 Z4.59 F2095.936 E101.148
G1 X-5.5 Y-1.18 Z4.59 F2095.936 E101.314
G1 F1200.0
G1 E101.314
G1 F2095.936
M103
M73 P81 (display progress)
(</loop>)
(<edge> outer )
;M108 R17.47
G1 X-5.9 Y-1.98 Z4.59 F6600.0
G1 F1200.0
G1 E101.314
G1 F6600.0
M101
G1 X-5.9 Y-2.05 Z4.59 F1047.968 E101.318
G1 X-5.5 Y-2.05 Z4.59 F1047.968 E101.341
G1 X5.9 Y-2.05 Z4.59 F1047.968 E102.011
G1 X5.9 Y2.05 Z4.59 F1047.968 E102.251
G1 X-5.9 Y2.05 Z4.59 F1047.968 E102.944
G1 X-5.9 Y-1.98 Z4.59 F1047.968 E103.18
M73 P82 (display progress)
G1 F1200.0
G1 E102.18
G1 F1047.968
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z2.85 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z2.85 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z2.85 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z2.85 </infillPoint>)
(</infillBoundary>)
;M108 R34.93
M73 P83 (display progress)
G1 X5.16 Y-1.2 Z4.59 F6600.0
G1 F1200.0
G1 E103.18
G1 F6600.0
M101
G1 X-5.16 Y-1.2 Z4.59 F2095.936 E103.786
G1 X-5.22 Y-0.8 Z4.59 F2095.936 E103.81
G1 X5.22 Y-0.8 Z4.59 F2095.936 E104.423
G1 X5.22 Y-0.4 Z4.59 F2095.936 E104.446
G1 X-5.22 Y-0.4 Z4.59 F2095.936 E105.059
G1 X-5.22 Y0.0 Z4.59 F2095.936 E105.083
G1 X5.22 Y-0.0 Z4.59 F2095.936 E105.695
G1 X5.22 Y0.4 Z4.59 F2095.936 E105.719
G1 X-5.22 Y0.4 Z4.59 F2095.936 E106.331
M73 P84 (display progress)
G1 X-5.22 Y0.8 Z4.59 F2095.936 E106.355
G1 X5.22 Y0.8 Z4.59 F2095.936 E106.968
G1 X5.16 Y1.2 Z4.59 F2095.936 E106.991
G1 X-5.16 Y1.2 Z4.59 F2095.936 E107.597
G1 F1200.0
G1 E106.597
G1 F2095.936
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R35.44
(</layer>)
(<layer> 4.89 )
M73 P85 (display progress)
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z4.89 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z4.89 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z4.89 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z4.89 </boundaryPoint>)
(<loop> outer )
G1 X-5.48 Y-1.65 Z4.89 F6600.0
G1 F1200.0
G1 E107.597
G1 F6600.0
M101
G1 X5.5 Y-1.65 Z4.89 F2126.488 E108.242
M73 P86 (display progress)
G1 X5.5 Y1.65 Z4.89 F2126.488 E108.435
G1 X-5.5 Y1.65 Z4.89 F2126.488 E109.081
G1 X-5.5 Y-1.65 Z4.89 F2126.488 E109.275
G1 X-5.48 Y-1.65 Z4.89 F2126.488 E109.276
G1 F1200.0
G1 E109.276
G1 F2126.488
M103
(</loop>)
(<edge> outer )
;M108 R17.72
G1 X-5.48 Y-2.05 Z4.89 F6600.0
G1 F1200.0
G1 E109.276
M73 P87 (display progress)
G1 F6600.0
M101
G1 X5.9 Y-2.05 Z4.89 F1063.244 E109.944
G1 X5.9 Y2.05 Z4.89 F1063.244 E110.184
G1 X-5.9 Y2.05 Z4.89 F1063.244 E110.877
G1 X-5.9 Y-2.05 Z4.89 F1063.244 E111.118
G1 X-5.5 Y-2.05 Z4.89 F1063.244 E111.141
G1 X-5.48 Y-2.05 Z4.89 F1063.244 E111.142
G1 F1200.0
G1 E111.142
G1 F1063.244
M103
(</edge>)
(</boundaryPerimeter>)
M73 P88 (display progress)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z3.15 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z3.15 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z3.15 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z3.15 </infillPoint>)
(</infillBoundary>)
;M108 R35.44
G1 X-5.2 Y-1.16 Z4.89 F6600.0
G1 F1200.0
G1 E111.142
G1 F6600.0
M101
G1 X-5.2 Y1.16 Z4.89 F2126.488 E111.279
M73 P89 (display progress)
G1 X-4.8 Y1.37 Z4.89 F2126.488 E111.305
G1 X-4.8 Y-1.37 Z4.89 F2126.488 E111.466
G1 X-4.4 Y-1.37 Z4.89 F2126.488 E111.489
G1 X-4.4 Y1.37 Z4.89 F2126.488 E111.65
G1 X-4.0 Y1.37 Z4.89 F2126.488 E111.674
G1 X-4.0 Y-1.37 Z4.89 F2126.488 E111.835
G1 X-3.6 Y-1.37 Z4.89 F2126.488 E111.858
G1 X-3.6 Y1.37 Z4.89 F2126.488 E112.019
G1 X-3.2 Y1.37 Z4.89 F2126.488 E112.042
G1 X-3.2 Y-1.37 Z4.89 F2126.488 E112.203
G1 X-2.8 Y-1.37 Z4.89 F2126.488 E112.227
G1 X-2.8 Y1.37 Z4.89 F2126.488 E112.387
G1 X-2.4 Y1.37 Z4.89 F2126.488 E112.411
G1 X-2.4 Y-1.37 Z4.89 F2126.488 E112.572
M73 P90 (display progress)
G1 X-2.0 Y-1.37 Z4.89 F2126.488 E112.595
G1 X-2.0 Y1.37 Z4.89 F2126.488 E112.756
G1 X-1.6 Y1.37 Z4.89 F2126.488 E112.779
G1 X-1.6 Y-1.37 Z4.89 F2126.488 E112.94
G1 X-1.2 Y-1.37 Z4.89 F2126.488 E112.964
G1 X-1.2 Y1.37 Z4.89 F2126.488 E113.125
G1 X-0.8 Y1.37 Z4.89 F2126.488 E113.148
G1 X-0.8 Y-1.37 Z4.89 F2126.488 E113.309
G1 X-0.4 Y-1.37 Z4.89 F2126.488 E113.332
G1 X-0.4 Y1.37 Z4.89 F2126.488 E113.493
G1 X0.0 Y1.37 Z4.89 F2126.488 E113.517
G1 X-0.0 Y-1.37 Z4.89 F2126.488 E113.677
G1 X0.4 Y-1.37 Z4.89 F2126.488 E113.701
G1 X0.4 Y1.37 Z4.89 F2126.488 E113.862
M73 P91 (display progress)
G1 X0.8 Y1.37 Z4.89 F2126.488 E113.885
G1 X0.8 Y-1.37 Z4.89 F2126.488 E114.046
G1 X1.2 Y-1.37 Z4.89 F2126.488 E114.07
G1 X1.2 Y1.37 Z4.89 F2126.488 E114.23
G1 X1.6 Y1.37 Z4.89 F2126.488 E114.254
G1 X1.6 Y-1.37 Z4.89 F2126.488 E114.415
G1 X2.0 Y-1.37 Z4.89 F2126.488 E114.438
G1 X2.0 Y1.37 Z4.89 F2126.488 E114.599
G1 X2.4 Y1.37 Z4.89 F2126.488 E114.622
G1 X2.4 Y-1.37 Z4.89 F2126.488 E114.783
G1 X2.8 Y-1.37 Z4.89 F2126.488 E114.807
G1 X2.8 Y1.37 Z4.89 F2126.488 E114.968
G1 X3.2 Y1.37 Z4.89 F2126.488 E114.991
G1 X3.2 Y-1.37 Z4.89 F2126.488 E115.152
M73 P92 (display progress)
G1 X3.6 Y-1.37 Z4.89 F2126.488 E115.175
G1 X3.6 Y1.37 Z4.89 F2126.488 E115.336
G1 X4.0 Y1.37 Z4.89 F2126.488 E115.36
G1 X4.0 Y-1.37 Z4.89 F2126.488 E115.52
G1 X4.4 Y-1.37 Z4.89 F2126.488 E115.544
G1 X4.4 Y1.37 Z4.89 F2126.488 E115.705
G1 X4.8 Y1.37 Z4.89 F2126.488 E115.728
G1 X4.8 Y-1.37 Z4.89 F2126.488 E115.889
G1 X5.2 Y-1.16 Z4.89 F2126.488 E115.915
G1 X5.2 Y1.16 Z4.89 F2126.488 E116.052
G1 F1200.0
G1 E115.052
G1 F2126.488
M103
M73 P93 (display progress)
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R34.93
(</layer>)
(<layer> 5.19 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-6.1 Y-2.25 Z5.19 </boundaryPoint>)
(<boundaryPoint> X6.1 Y-2.25 Z5.19 </boundaryPoint>)
(<boundaryPoint> X6.1 Y2.25 Z5.19 </boundaryPoint>)
(<boundaryPoint> X-6.1 Y2.25 Z5.19 </boundaryPoint>)
(<loop> outer )
M73 P94 (display progress)
G1 X-5.5 Y-1.37 Z5.19 F6600.0
G1 F1200.0
G1 E116.052
G1 F6600.0
M101
G1 X-5.5 Y-1.65 Z5.19 F2096.056 E116.069
G1 X5.5 Y-1.65 Z5.19 F2096.056 E116.714
G1 X5.5 Y1.65 Z5.19 F2096.056 E116.908
G1 X-5.5 Y1.65 Z5.19 F2096.056 E117.553
G1 X-5.5 Y-1.37 Z5.19 F2096.056 E117.73
G1 F1200.0
G1 E117.73
G1 F2096.056
M103
M73 P95 (display progress)
(</loop>)
(<edge> outer )
;M108 R17.47
G1 X-5.78 Y-2.05 Z5.19 F6600.0
G1 F1200.0
G1 E117.73
G1 F6600.0
M101
G1 X-5.5 Y-2.05 Z5.19 F1048.028 E117.747
G1 X5.9 Y-2.05 Z5.19 F1048.028 E118.416
G1 X5.9 Y2.05 Z5.19 F1048.028 E118.657
G1 X-5.9 Y2.05 Z5.19 F1048.028 E119.35
G1 X-5.9 Y-2.05 Z5.19 F1048.028 E119.59
G1 X-5.78 Y-2.05 Z5.19 F1048.028 E119.597
M73 P96 (display progress)
G1 F1200.0
G1 E118.597
G1 F1048.028
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-5.5 Y-1.65 Z3.45 </infillPoint>)
(<infillPoint> X5.5 Y-1.65 Z3.45 </infillPoint>)
(<infillPoint> X5.5 Y1.65 Z3.45 </infillPoint>)
(<infillPoint> X-5.5 Y1.65 Z3.45 </infillPoint>)
(</infillBoundary>)
;M108 R34.93
M73 P97 (display progress)
G1 X5.16 Y-1.2 Z5.19 F6600.0
G1 F1200.0
G1 E119.597
G1 F6600.0
M101
G1 X-5.16 Y-1.2 Z5.19 F2096.056 E120.203
G1 X-5.22 Y-0.8 Z5.19 F2096.056 E120.227
G1 X5.22 Y-0.8 Z5.19 F2096.056 E120.839
G1 X5.22 Y-0.4 Z5.19 F2096.056 E120.863
G1 X-5.22 Y-0.4 Z5.19 F2096.056 E121.476
G1 X-5.22 Y0.0 Z5.19 F2096.056 E121.499
G1 X5.22 Y-0.0 Z5.19 F2096.056 E122.112
G1 X5.22 Y0.4 Z5.19 F2096.056 E122.135
G1 X-5.22 Y0.4 Z5.19 F2096.056 E122.748
M73 P98 (display progress)
G1 X-5.22 Y0.8 Z5.19 F2096.056 E122.771
G1 X5.22 Y0.8 Z5.19 F2096.056 E123.384
G1 X5.16 Y1.2 Z5.19 F2096.056 E123.408
G1 X-5.16 Y1.2 Z5.19 F2096.056 E124.014
G1 F1200.0
G1 E123.014
G1 F2096.056
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R85.0
(</layer>)
(</crafting>)
M73 P99 (display progress)
M104 S0
;M113 S0.0
M127
(******* End.gcode*******)
M73 P100 ( End  build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
M104 S0 T0 ( Cool down the Right Extruder )
M109 S0 T0 ( Cool down the platform)
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
